### ISSUE TITLE
TP Authentication Failed

### ISSUE THREAD

**Issue by SrPeterr** [enjin/enjincraft#93]
Hi!
The plugin should be working on 1.17 right?

I tried to go on 1.16.5 and I get this error:
```
[17:40:01] [Server thread/INFO]: {"errors":[{"message":"The given data was invalid.","code":422,"validation":{"id":["The selected id is invalid."]}}],"data":{"result":null}}
[17:40:01] [Server thread/INFO]: <-- END HTTP (140-byte body)
[17:40:01] [Server thread/WARN]: [EnjinCraft] Exception Caught
com.enjin.enjincraft.spigot.AuthenticationException: Error Code 422 - TP Authentication Failed
	at com.enjin.enjincraft.spigot.SpigotBootstrap.authenticateTPClient(SpigotBootstrap.java:160) ~[?:?]
	at com.enjin.enjincraft.spigot.SpigotBootstrap.setUp(SpigotBootstrap.java:89) ~[?:?]
	at com.enjin.enjincraft.spigot.EnjPlugin.onEnable(EnjPlugin.java:15) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

Trying on 1.17 or 1.17.1:
```
[17:51:42] [Server thread/ERROR]: Error occurred while enabling EnjinCraft v1.1.1-spigot (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:184) ~[?:?]
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173) ~[?:?]
	at com.enjin.enjincraft.spigot.libs.retrofit2.Retrofit$Builder.<init>(Retrofit.java:441) ~[?:?]
	at com.enjin.sdk.TrustedPlatformClientImpl.<init>(TrustedPlatformClientImpl.java:162) ~[?:?]
	at com.enjin.sdk.TrustedPlatformClientBuilder.build(TrustedPlatformClientBuilder.java:153) ~[?:?]
	at com.enjin.enjincraft.spigot.SpigotBootstrap.setUp(SpigotBootstrap.java:87) ~[?:?]
	at com.enjin.enjincraft.spigot.EnjPlugin.onEnable(EnjPlugin.java:15) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) [spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) [spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) [spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608) [spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) [spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) [spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) [spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.MinecraftServer$$Lambda$3834/0x000000002c0dc4e0.run(Unknown Source) [spigot-1.17.jar:3149-Spigot-101ebb6-9122f5a]
	at java.lang.Thread.run(Thread.java:853) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int) accessible: module java.base does not "opens java.lang.invoke" to unnamed module @6f161465
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188) ~[?:?]
	at java.lang.reflect.Constructor.setAccessible(Constructor.java:181) ~[?:?]
	at com.enjin.enjincraft.spigot.libs.retrofit2.Platform.<init>(Platform.java:59) ~[?:?]
	at com.enjin.enjincraft.spigot.libs.retrofit2.Platform.findPlatform(Platform.java:44) ~[?:?]
	at com.enjin.enjincraft.spigot.libs.retrofit2.Platform.<clinit>(Platform.java:35) ~[?:?]
	... 16 more
```

The app id and secret are correct.
And the dev-address should be my wallet address, no?

**Comment by SrPeterr** [comment]
Solved, forgot to change the `base-url` 🤔

**Comment by orxhqq** [comment]
> Solved, forgot to change the `base-url` 🤔


Hi, I had the same error, but I don't know what to put in the base-url
